### ISSUE TITLE
Proprio for single arm

### ISSUE THREAD

**Issue by jonathonsather-bc** [rail-berkeley/crossformer#4]
Looking at `pretrain_config.py`, I only see proprio observation tokenizers for bimanual and quadruped. Is there a reason there is no proprio tokenizer for single-arm (or did I miss it)? 

Follow-up question: If I want to include single-arm proprio inputs during fine-tuning, would you recommend defining a new observation tokenizer, or passing the values into the bimanual tokenizer (e.g. pretend there are two identical arms)?

**Comment by HomerW** [comment]
Yeah we didn't use proprio for single arms. For fine-tuning with single-arm prorio, I think adding a new observation tokenizer will probably work just as well as re-using the bimanual proprio tokenizer. The proprio tokenizers are pretty light-weight.
